{{- if not (or .Values.valkey.enabled (and .Values.tasksRedis.existingSecretName .Values.cachingRedis.existingSecretName)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "valkey" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ if not .Values.tasksRedis.existingSecretName -}}
  redis_tasks_password: {{ .Values.tasksRedis.password | b64enc | quote }}
  {{ end -}}
  {{ if not .Values.cachingRedis.existingSecretName -}}
  redis_cache_password: {{ .Values.cachingRedis.password | b64enc | quote }}
  {{ end -}}
{{- end -}}
